apiVersion: v1
kind: Service
metadata:
  name: {{ include "kpi-claim-web-nuxt.fullname" . }}
  labels:
    {{- include "kpi-claim-web-nuxt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort"}}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "kpi-claim-web-nuxt.selectorLabels" . | nindent 4 }}
